spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cms?characterEncoding=utf-8&useSSL=true
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 5
      max-active: 30
      min-idle: 5
      max-wait: 60000
